version: '3'
services:
  app:
    container_name: bee_mely
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=${NODE_ENV}
      - DEV_APP_PORT=${DEV_APP_PORT}
      - PRO_APP_PORT=${PRO_APP_PORT}
      - DEV_DB_URL=${DEV_DB_URL}
      - PRO_DB_URL=${PRO_DB_URL}
      - MAIL_ADMIN=${MAIL_ADMIN}
      - MAIL_PASS=${MAIL_PASS}
      - ACCESS_SECRET=${ACCESS_SECRET}
      - REFRESH_SECRET=${REFRESH_SECRET}
      - CLIENT_BASE_URL=${CLIENT_BASE_URL}
      - CLOUD_NAME=${CLOUD_NAME}
      - API_KEY=${API_KEY}
      - API_SECRET=${API_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - DEFAULT_TIMEZONE=${DEFAULT_TIMEZONE}
    ports:
      - '${DEV_APP_PORT}:${DEV_APP_PORT}'
    command: npm start
